apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pong-hpa
  namespace: apps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pong-dep # name of the deployment this acts on
  minReplicas: 1
  maxReplicas: 4 # NB that the deployment had replicas: 1
  targetCPUUtilizationPercentage: 50